- hosts: localhost
  become: true
  pre_tasks:
    - name: reflector my ass
      pacman:
        name: reflector
      tags:
      - core
    - name: mirror diz nutz
      shell: reflector --save /etc/pacman.d/mirrorlist --country Poland --protocol http,https
    - name: Update pacman
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
      - core
      - term
      - chad
  ansible.buildin.include_tasks:
    - file: tasks/git-setup.yml
    - file: tasks/ssh.yml
    - file: tasks/dotfiles.yml
    - file: tasks/term.yml
    - file: tasks/nvim.yml
    - file: tasks/productivity.yml
