- name: Install zsh
  pacman: 
    name: zsh
    state: present
  tags: 
  - term
  - core

- name: OhMyFish disnuts
  shell: chsh -s /bin/zsh

- name: Install tmux
  pacman: 
    name: tmux
    state: present
  tags: 
  - term
  - core
